var posturl;
posturl = {
  host: 'http://xchcar.com/served',
  basePicUrl: '',
  shopSum: '/admin/sum/shopSum',
  shopList: '/admin/shop/lists',
  projectSum: '/admin/sum/projectSum',
  userSum: '/admin/sum/userSum',
  managerLists: '/admin/admin/lists',
  managerEdit: '/admin/admin/edit',
  managerAdd: '/admin/admin/add',
  managerDel: '/admin/admin/del',
  managerFind: '/admin/admin/find',
  projectList: '/admin/project/lists',
  projectEdit: '/admin/project/edit',
  projectAdd: '/admin/project/add',
  projectDel: '/admin/project/del',
  projectFind: '/admin/project/find',
  carTypeList: '/admin/vehicle_series/lists',
  carTypeEdit: '/admin/vehicle_series/edit',
  carTypeDel: '/admin/vehicle_series/del',
  carTypeFind: '/admin/vehicle_series/find',
  carTypeAdd: '/admin/vehicle_series/add',
  brandFind: '/admin/vehicle_brand/find',
  carClassify: '/admin/vehicle_Sort/lists',
  brandLists: '/admin/vehicle_brand/lists',
  brandEdit: '/admin/Vehicle_Brand/edit',
  brandAdd: '/admin/Vehicle_Brand/add',
  brandDel: '/admin/Vehicle_Brand/del',
  consumeDetails: '/admin/sum/details',
  nameFind: '/admin/sum/nameFind',
  phoneFind: '/admin/sum/phoneFind',
  SortEdit: '/admin/vehicle_sort/edit',
  SortDel: '/admin/vehicle_sort/del',
  SortAdd: '/admin/vehicle_sort/add',
  ShopEdit: '/admin/shop/edit',
  ShopAdd: '/admin/shop/add',
  ShopDel: '/admin/shop/del',
  ShortDetails: '/admin/Vehicle_Sort/details',
  feedbackList: '/admin/suggest/sumLists',
  orderList: '/admin/order/lists',
  OrderState: '/admin/order/state',
  findPlate: '/admin/order/findPlate',
  findOrderByPlate: '/admin/order/find_order',
  adminLogin: '/admin/admin/login',
  modifyPwd: '/admin/admin/editPwd',
  brandOrderList: '/admin/order/aloneLists',
  undoneOrderList: '/admin/order/undoneOrder',
  brandProjectSum: '/admin/Sum_part/projectSum',
  brandProUserSum: '/admin/Sum_part/userSum',
  brandNameFind: '/admin/Sum_part/nameFind',
  brandPhoneFind: '/admin/Sum_part/phoneFind',
  sortFind: '/admin/Sum_part/sortFind',
  export: '/admin/order/export',
  findOrder: '/admin/order/findOrder',


};

global.posturl = posturl;
